[package]
name = "jvm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.17"
rustop = "1.1.2"
javaclass-rs = { path = "../javaclass-rs" }
zip = "0.6.3"
